### ISSUE TITLE
deckz fill

### ISSUE THREAD

**Issue by nzmonzmp** [m09/deckz#13]
Ce serait pas plus utile de copier les sources venant de .../share/latex/ dans les dossiers afin de bosser  sur des version locales à la formation courante ? Si je pige bien pour l'instant il utilise des liens symboliques ?

**Comment by m09** [comment]
Ça peut être cool oui. Pour moi le souci si on fait ça c'est qu'on va jamais mettre à jour les trucs dans shared si on voit des conneries dans les slides, on va mettre à jour que dans le dossier de la formation et on va pas prendre le temps d'aller fix le dossier shared, et ça tue un peu son intérêt.

J'peux faire en sorte que ça soit spécifiable dans le targets.yml si on veut des liens pour certains et pas de liens pour d'autres parce que trop spécifique à la formation.

**Comment by nzmonzmp** [comment]
Tu peux faire en sorte que ça update les shared/latex/ à chaque deckz run. Comme ça plus besoin d'aller fouiller dans targets.xml pour savoir quels fichiers sont à éditer, tout est dans j1/ j2/ j3/ , non ?

**Comment by m09** [comment]
du coup je mets directement les liens symboliques dans les dossiers des targets si tu veux, en plus de dans le dossier de build

**Comment by nzmonzmp** [comment]
habile !

**Comment by m09** [comment]
Je ferme celle-là, elle est obsolète avec la 3.0, on en recréera une si il faut :)
