### ISSUE TITLE
sections versioning

### ISSUE THREAD

**Issue by nzmonzmp** [m09/deckz#38]
ajout d'un attribut aux sections permettant de gérer des versions plus ou moins complètes de la section
du genre 
`
- name: j1
  title: "Vue d'ensemble des enjeux de l'Intelligence Artificielle"
  sections:
    - title: "Les mécanismes du Machine Learning"
      path: ml
      version: cours

    - title: "Les Réseaux de neurones"
      path: nn-intro

    - path: cnn
      version: approfondie
`

Les tag de version seraient notés dans le section.yml

**Comment by nzmonzmp** [comment]
utilisations de tag plutôt que de version

**Comment by nzmonzmp** [comment]
quand on deckz run, ça serait cool :
`
IF [manque un fichier décrit dans section.yml] THEN recherche dans shared/ (genre pour le slide question.tex, relou de le copier dans chaque section) IF [toujours pas trouvé] création d'un template.
`
Ça résolvrait l'issue deckz fill au passage.

**Comment by m09** [comment]
J'préfère laisser le fill séparé. C'est bien d'avoir des erreurs aussi de temps en temps plutôt que la création de templates en silence quand on fait de la merde.

**Comment by nzmonzmp** [comment]
ça se défend
