### ISSUE TITLE
deckz fill

### ISSUE THREAD

**Issue by nzmonzmp** [m09/deckz#43]
disparu ? :-(

**Comment by m09** [comment]
Je ferme celle-là parce que je pense que c'est toujours plus rapide de C/C un targets.yml existant proche de ce qu'on veut faire et de l'éditer mais si tu penses qu'il y a un `deckz fill` malin qui aurait du sens hésite pas à commenter !

**Comment by nzmonzmp** [comment]
C'est pas faux 😄
