### ISSUE TITLE
deckz init

### ISSUE THREAD

**Issue by nzmonzmp** [m09/deckz#50]
target.yml template is v1. need v2

**Comment by m09** [comment]
Pour moi il est bien : https://github.com/m09/formations/blob/master/templates/targets.yml. Non ?

**Comment by nzmonzmp** [comment]
ça deckz run pas avec ça, pour moi ça a finit par compiler avec ça :

- name: j1
  title: Jour 1 --- Titre
  sections:
    - title: Titre
      path: machine-learning
      flavor: intro
    - questions

et ce n'est pas juste un problème de flavor, le include ça fait très v1 ;-)

**Comment by m09** [comment]
En effet. Pour ça d'façon y a pas besoin de modifier deckz, c'est dans `templates` dans les repo utilisateurs.

**Comment by nzmonzmp** [comment]
effectivement, je m'occupe de la modif ;-)

Tu as 5mn pour un besoin spécifique deckz ?
si ok go meet.
